### ISSUE TITLE
请求增加生成纯文本封面的功能

### ISSUE THREAD

**Issue by waleslau** [ystyle/kaf-cli#19]
大概思路是如果目录下没有`cover.png`文件，并且也没有在命令中手动指定封面图片，则自动为生成的 epub 等格式添加纯文本的封面。

`cover.css`：
~~从 easypub 生成的 epub 文件里扒过来的样式表~~

```css
.bookname {
  margin-top: 30%;
  margin-bottom: 0;
  border-style: none solid none none;
  border-width: 50px;
  border-color: #4e594d;
  font-size: 3em;
  line-height: 120%;
  text-align: right;
}

.bookauthor {
  margin-top: 0;
  border-style: none solid none none;
  border-width: 50px;
  border-color: #4e594d;
  page-break-after: always;
  font-size: large;
  line-height: 120%;
  text-align: right;
}
```

对应的`cover.xhtml`的 body 部分：

```html
<body>
  <div>
    <h1 class="bookname">Bookname</h1>
    <h3 class="bookauthor">Author</h3>
  </div>
</body>
```

封面效果如图所示

![](https://files.catbox.moe/y5pjuu.png)

思路再放飞一下，作者大大也可以开放自定义 css 功能，比如加一个引入自定义样式表的参数:satisfied:
